// contains quote details

const quoteStatements = [
  {
    firstSentenceFragment: [
      'In wine there is wisdom,',
      'Wine and cheese are ageless companions,',
      'I have made a lot of mistakes falling in love,',
      'One cannot think well,',
      'If you really want to make a friend,',
      'Vegetables are a must on a diet,',
      'I\'m not a chef,',
      'If you want to become a great chef,',
      'Anyone who\'s a chef, who loves food,',
      'You could probably get through life,',
      'Learning to season in cooking,',
      'When you\'re running a restaurant,',
      'Never work before breakfast;',
      'If you have extraordinary bread,',
      'Food brings people together on many different levels,',
      'It\'s not about what home cooks know;',
      'After a good dinner,',
      'Pull up a chair,',
      'Popcorn for breakfast! Why not? It\'s a grain,',
      'What I say is that,',
      'My love is pizza shaped,',
      'Humor keeps us alive,',
      'If this is coffee,',
      'I love food,',
      'Food feeds both the body and soul –',
      'I like food,',
    ],
    middleSentenceFragment: [
      'in beer there is strength,',
      'like aspirin and aches, or June and moon,',
      'and regretted most of them,',
      'love well, sleep well,',
      'go to someone\'s house and eat with him...',
      'I suggest carrot cake,',
      'but I\'m passionate about food -',
      'you have to work with great chefs,',
      'ultimately knows that all that matters is:',
      'without knowing how to roast a chicken,',
      'is like learning to stickhandle in hockey;',
      'you have to change with the times;',
      'if you have to work before breakfast,',
      'and extraordinary butter,',
      'It\'s nourishment of the soul and body;',
      'anyone can cook,',
      'one can forgive anybody,',
      'take a taste. Come join us,',
      'it\'s like, like, grits,',
      'if a man really likes potatoes,',
      'won\'t you have a slice? It\'s circular,',
      'humor and food. Don\'t forget food,',
      'please bring me some tea;',
      'I\'m a big food person,',
      'there are clear reasons to eat a balanced diet,',
      'I like eating,',
    ],
    lastSentenceFragment: [
      'in water there is bacteria.',
      'or good people and noble ventures.',
      'but never the potatoes that went with them.',
      'if one has not dined well.',
      'the people who give you their food give you their heart.',
      'zucchini bread and pumpkin pie.',
      'the tradition of it, cooking it, and sharing it.',
      'and that\'s exactly what I did.',
      '\'Is it good? Does it give pleasure?',
      'but the question is, would you want to?',
      'it\'s absolutely fundamental.',
      'otherwise, the times will change you.',
      'eat your breakfast first.',
      'it\'s hard to beat bread and butter.',
      'it\'s truly love.',
      'It\'s about enjoying the fun of creation!',
      'even one\'s own relations.',
      'life is so endlessly delicious.',
      'but with high self-esteem.',
      'he must be a pretty decent sort of fellow.',
      'so there\'s enough to go around.',
      'you can go a week without laughing.',
      'but if this is tea, please bring me some coffee.',
      'I\'m really passionate about eating good food all the time.',
      'but there are reasons you cling to your mom\'s chicken noodle soup',
      'and I don\'t want to deprive myself of good food.',
    ],
  },
  {
    firstSentenceFragment: [
      'What you wear is how you present yourself to the world;',
      'I think there is beauty in everything;',
      'Fashion is very important -',
      'You can never take too much care over the choice of your shoes- ',
      'Style is the only thing you can\'t buy-',
      'What\'s my style is not your style,',
      'Girls do not dress for boys,',
      'A little bad taste is like a nice splash of paprika...',
      'The customer is the final filter-',
      'I have always believed fashion was not only to make women beautiful,',
      'When you hear designers complain about the challenge of their careers,',
      'Fashion is not necessarily about labels,',
      'When I first moved to New York, and I was totally broke,',
      'In a machine age,',
      'Fashion,',
      'I adore wearing gems, but not because they are mine-',
      'Too much good taste can be very boring-',
      'I don\'t believe in fashion,',
      'There was a photo of me with weird sunglasses and a green sweatshirt,',
      'I really would not call myself a fashion icon,',
      'Women think of all colors except the absence of color-',
    ],
    middleSentenceFragment: [
      'especially today, when human contacts are so quick,',
      'what \'normal\' people perceive as ugly,',
      'it is life-enhancing and, like everything that gives pleasure,',
      'too many women think that they are unimportant,',
      'it\'s not in a shopping bag, a label, or a price tag-',
      'and I don\'t see how you can define it,',
      'they dress for themselves, and of course, each other-',
      'it\'s healthy, it\'s physical. I think we could use more of it-',
      'what survives the whole process is what people wear-',
      'but also to reassure them,',
      'you have to say: Don\'t get carried away-',
      'it\'s not about brands, ',
      'sometimes I would buy Vogue instead of dinner-',
      'dressmaking is one of the last refuges of the human,',
      'somehow for me,',
      'you can\'t possess radiance,',
      'independent style, on the other hand,',
      'I believe in costume-',
      'some striped thing, with tights and cowboy boots...',
      'I would call myself somebody who gets dressed by professionals...',
      'I have said that black has it all. White too. Their beauty is absolute-',
    ],
    lastSentenceFragment: [
      'fashion is instant language.',
      'I can usually see something of beauty in it.',
      'it is worth doing well.',
      'but the real proof of an elegant woman is what is on her feet.',
      'it\'s something reflected from our soul.',
      'it\'s something that expresses who you are in your own way.',
      'if girls dressed for boys, they\'d just walk around naked.',
      'no taste is what I\'m against.',
      'I\'m not interested in making clothes that end up in some dusty museum.',
      'give them confidence.',
      'it\'s only dresses.',
      'it\'s about something else that comes from within you.',
      'I felt it fed me more.',
      'the personal, the inimitable.',
      'is purely and happily irrational.',
      'you can only admire it.',
      'can be very inspiring.',
      'life is too short to be the same person every day.',
      'I just saw that photo and thought, God, I look crazy.',
      'I would call me more of a monkey.',
      'it is the perfect harmony.',
    ],
  },
  {
    firstSentenceFragment: [
      'Don\'t let the rain drive you to the wrong shelter;',
      'Shade for a man and shelter for animals,',
      'Inside each of us are memories,',
      'We owe shelter and welfare to people who were either born here,',
      'Everyone is in need of a shelter from the storm,',
      'Karma yoga is giving food to the hungry,',
      'Maybe,',
      'I\'ll be your blanket, baby,',
      'Thus bound together,',
      'Be thankful,',
      'People are lucky because they have shelters,',
      'Life begins well,',
      'In a novel,',
      'I would suggest that the prisons I create are not to lock me in,',
      'Madness is like an alternative residence,',
      'Each evening, I ached for the shelter of my tent,',
      'Perhaps love is like a resting place,',
      'You should avoid seeing too much of yourself anywhere:',
      'I don\'t know what\'s worse by number in America,',
      'This life will never be without storms,',
      'What we actually need,',
    ],
    middleSentenceFragment: [
      'the shade can turn out to be your protector and also your destroyer,',
      'planted in your name,',
      'fantasies and desires for home - a shelter waiting to be built,',
      'or people who show a desire to... become useful members of society,',
      'be the shelter,',
      'clothes to the needy,',
      'someday we all will come out of those beautiful and warm shelters,',
      'wrap yourself up in me,',
      'they sheltered the child from the cold, dark night,',
      'that you have clothes to wear,',
      'they have refuges,',
      'it begins enclosed, protected,',
      'you\'ll find yourself in a world of possibilities,',
      'rather they are designed to lock the world out, and either way,',
      'when sanity chases you out of home,',
      'for the smallest sense that something was shielding me from the world,',
      'a shelter from the storm - it exists to give you comfort...',
      'in the outside world, in others,',
      'the vacant houses standing,',
      'stop fearing the storm,',
      'food, clothing and shelter,',
    ],
    lastSentenceFragment: [
      'and sometimes the rain is the perfect protector from the rain.',
      'may you be the same for those around you',
      'a place of peace to be revisited.',
      'and certainly, nobody else.',
      'be kind.',
      'shelter to the homeless.',
      'we have built around us and open our arms to the storms, and smiling.',
      'let me give you shelter, in the winter of this world.',
      'enveloping him in warmth.',
      'food to eat and a place to sleep.',
      'they have sanctuaries and they have heavens!',
      'all warm in the bosom of the house.',
      'you\'ll find shelter there.',
      'I am a prisoner who has sentenced himself to a prison I do not belong.',
      'take shelter in madness.',
      'keeping me safe not from danger, but from vastness itself.',
      'the memory of love will bring you home.',
      'in the imagined worlds that give you shelter.',
      'or the homeless people falling into them.',
      'build your inner shelter.',
      'everything else is entertainment.',
    ],
  },
];

const quoteAuthors = [
  {
    firstName: [
      'David',
      'M.F.K.',
      'Nora',
      'Virginia',
      'Cesar',
      'Jim',
      'Zac',
      'Gordon',
      'Anthony',
      'Nigella',
      'Rob',
      'Gordon',
      'Josh',
      'Jacques',
      'Giada',
      'Christos',
      'Oscar',
      'Ruth',
      'James',
      'A.A.',
      'Dora',
      'Joss',
      'Abraham',
      'Dreama',
      'Michael',
      'Sarah',
    ],

    lastName: [
      'Auerbach',
      'Fisher',
      'Ephron',
      'Woolf',
      'Chavez',
      'Davis',
      'Posen',
      'Ramsay',
      'Bourdain',
      'Lawson',
      'Feenie',
      'Ramsay',
      'Billings',
      'Pepin',
      'De Laurentiis',
      'Athanasiadis',
      'Wilde',
      'Reichl',
      'Patterson',
      'Milne',
      'J. Arod',
      'Whedon',
      'Lincoln',
      'Walker',
      'Mina',
      'Michelle Gellar',
    ],
  },
  {
    firstName: [
      'Miuccia',
      'Alexander',
      'Vivienne',
      'Christian',
      'Alber',
      'Iris',
      'Betsey',
      'Diana',
      'Marc',
      'Yves',
      'Karl',
      'Ralph',
      'Carrie',
      'Christian',
      'Hedi',
      'Elizabeth',
      'Diana',
      'Stephanie',
      'Mary-Kate',
      'Jennifer',
      'Coco',
    ],
    lastName: [
      'Prada',
      'McQueen',
      'Westwood',
      'Dior',
      'Elbaz',
      'Apfel',
      'Johnson',
      'Vreeland',
      'Jacobs',
      'Saint Laurent',
      'Lagerfeld',
      'Lauren',
      'Bradshaw',
      'Dior',
      'Slimane',
      'Taylor',
      'Vreeland',
      'Perkins',
      'Olsen',
      'Lawrence',
      'Chanel',
    ],
  },
  {
    firstName: [
      'Michael B',
      'Nancy J.',
      'Louisa T.',
      'Karl',
      'Luffina',
      'Amit',
      'Akshay',
      'John Mark',
      'Seth A.',
      'Lailah G.',
      'Mehmet M.',
      'Gaston',
      'Alice',
      'Craig D.',
      'Munia',
      'Cheryl',
      'John',
      'John',
      'Anthony',
      'Yasmin',
      'Aloe',
    ],
    lastName: [
      'Johnson',
      'Cavanaugh',
      'Brits',
      'Wiggins',
      'Lourduraj',
      'Ray',
      'Vasu',
      'Green',
      'Smith',
      'Akita',
      'ildan',
      'Bachelard',
      'Hoffman',
      'Lounsbrough',
      'Khan',
      'Strayed',
      'Denver',
      'Darnielle',
      'Liccione',
      'Mogahed',
      'Blacc',
    ],
  },
];

const quotes = {
  categories: ['food', 'fashion', 'shelter'],
  foodQuotes: quoteStatements[0],
  fashionQuotes: quoteStatements[1],
  shelterQuotes: quoteStatements[2],
  foodQuoteAuthors: quoteAuthors[0],
  fashionQuoteAuthors: quoteAuthors[1],
  shelterQuoteAuthors: quoteAuthors[2],
  quoteTags: {
    tags: ['on Food', 'on Fashion', 'on Shelter'],
    foodTag: function() {
      return this.tags[0];
    },
    fashionTag: function() {
      return this.tags[1];
    },
    shelterTag: function() {
      return this.tags[2];
    },
  },
};
